name: Gitleaks
description: Run Gitleaks
branding:
  color: purple
  icon: eye
inputs:
  config_path:
    description: "Path to config, relative to $GITHUB_WORKSPACE"
    required: false
    default: ".github/.gitleaks.toml"
outputs:
  result:
    description: "Gitleaks log output"
    value: ${{ steps.gitleaks.outputs.result }}
  exit_code:
    description: "Gitleaks exit code"
    value: ${{ steps.gitleaks.outputs.exit_code }}
runs:
  using: "composite"
  steps:
    - id: gitleaks
      run: ${{ github.action_path }}/entrypoint.sh ${{ inputs.config_path }}
      shell: bash
