name: Gitleaks
description: Run Gitleaks
branding:
  color: purple
  icon: eye
inputs:
  config_path:
    description: "Path to folder containing .gitleaks.toml inside your repository"
    required: false
    default: ""
outputs:
  result:
    description: "Gitleaks log output"
    value: ${{ steps.gitleaks.outputs.result }}
  exit_code:
    description: "Gitleaks exit code"
    value: ${{ steps.gitleaks.outputs.exit_code }}
runs:
  using: "composite"
  steps:
    - id: gitleaks
      run: |
        if [ -z "${{ inputs.config_path }}" ]
        then
              echo -e "\n\nUSING CONFIG ${GITHUB_ACTION_PATH}/.gitleaks.toml"
              ${GITHUB_ACTION_PATH}/entrypoint.sh ${GITHUB_ACTION_PATH}/.gitleaks.toml
        else
              echo -e "\n\nUSING CONFIG ${GITHUB_WORKSPACE}/${{ inputs.config_path }}/.gitleaks.toml"
              ${GITHUB_ACTION_PATH}/entrypoint.sh ${GITHUB_WORKSPACE}/${{ inputs.config_path }}/.gitleaks.toml
        fi
      shell: bash
